### ISSUE TITLE
Color problem with ILI9486

### ISSUE THREAD

**Issue by fabien17** [bkosciow/gfxlcd#20]
Hi,
First thank you for your work.
I'm using a waveshare 3.5"(https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(B)) and I didn't found how to use it with python, then I found your library.
Everything seems to work fine except the colors which are wrong on my setup.
When lauching gfxlcd/gfxlcd/demos/ili9486_image.py, this is what I get:
![unnamed](https://user-images.githubusercontent.com/38955107/39586715-09117d6e-4ef8-11e8-929c-603d91fbd346.jpg)
instead of 

![ili9486](https://user-images.githubusercontent.com/38955107/39586729-13afa6e2-4ef8-11e8-98dc-7814a82779ea.jpg)

I get an error in terminal too:
 $ python3 ./ili9486_image.py
/usr/local/lib/python3.5/dist-packages/gfxlcd-0.8.3-py3.5.egg/gfxlcd/driver/ili9486/spi.py:27: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.

What am I doing wrong?
Thank you for your help.
Fabien

**Comment by bkosciow** [comment]
Hi,

Seems that there is a problem with colour conversion. From what I see on producer's web it should work without any problem but sadly it is not :(

Let's try and see what colour is messed up, we will draw few rectangles like this:

o.background_color = (0, 0, 0)
o.fill_rect(0, 0, 50, 50)
o.background_color = (255, 0, 0)
o.fill_rect(50, 0, 100, 50)
o.background_color = (0, 255, 0)
o.fill_rect(100, 0, 150, 50)
o.background_color = (0, 0, 255)
o.fill_rect(150, 0, 200, 50)
o.background_color = (255, 255, 255)
o.fill_rect(0, 50, 50, 100)

Try to adjust this code and run it, then post a picture. 

And do not mind an error, I should add cleaning up at the end of demos but I forgot ;;

**Comment by fabien17** [comment]
Hi,
Thank you very much for you fast answer.

Here is the picture:
![unnamed](https://user-images.githubusercontent.com/38955107/39600761-114fabd6-4f20-11e8-803f-27692215d65e.jpg)

**Comment by bkosciow** [comment]
if we can get white and black that's good. 
what I can advise you is to use the attached example and play with array and R G B keys. maybe some combination will get it right. I have created a class that extends main ILI and gives us _convert_color to play with.
[er.zip](https://github.com/bkosciow/gfxlcd/files/1997726/er.zip)

**Comment by fabien17** [comment]
Hi,
Thank you again for your help.
As I'm really a newbie in python and all that lcd stuff, I do not really understand what to do :-)
Could you please give me an example of how may I have to use us_convert_color to play with colors combinations?

**Comment by bkosciow** [comment]
in this function you have an array with keys: R G B. try and swap than to G B R order. and try other combinations.
if you ever get a pure red green or blue colour remember the order and put it in this thread

**Comment by fabien17** [comment]
Hi,
thank you for your answer.
My screen is already dead... after 3 weeks.  this is not very good stuff.
I will come back for testing this color problem when waveshare send me a new one.
I hope next week.

Thank you again for the help
